### ISSUE TITLE
Ошибочка

### ISSUE THREAD

**Issue by MrLivixx** [sqdshcom/vimeinfo#3]
Если вбить ник которого нету в базе вайма, то сайт будет вечно-что искать
![image](https://user-images.githubusercontent.com/54632865/81513811-b9eaa800-9333-11ea-9237-141d97904ea2.png)

**Comment by M1chnt** [comment]
В целом ошибка то есть, но она не серьезная.

**Comment by vladciphersky** [comment]
Один баг зарождает ещё один.

**Comment by vladciphersky** [comment]
Пофиксил `Uncaught SyntaxError: Illegal return statement`:
- https://github.com/sqdshcom/vimeinfo/commit/542b5af743ba538ecc5492256d52a00db61dc91e
- https://github.com/sqdshcom/vimeinfo/commit/9ce38e68234b3af610c731c73228efd66dddee16
